# Generated by Django 4.1.3 on 2024-01-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destapi', '0003_activity_destact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
